services:
  tgbot-ttv:
    build: .
    command: >
      sh -c "
        echo 'Waiting 15 seconds before starting...';
        sleep 15;
        python manage.py migrate &&
        python run.py"
    networks:
      - tgbot_to_db
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - tgbot_to_db


networks:
  tgbot_to_db:
    driver: bridge
    internal: true

volumes:
  postgres_data:
