[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py39']
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | build
  | dist
  | pckgs
  | venv
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_django = "django"
sections = "FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER"
skip = ["migrations", "pckgs", "venv"]
