# Generated by Django 4.2.18 on 2025-02-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexer', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='from_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='indexer.contract'),
        ),
        migrations.AddField(
            model_name='rate',
            name='to_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='indexer.contract'),
        ),
        migrations.AddField(
            model_name='payment',
            name='related_model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bot.telegramuser'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user'], name='bot_subscri_user_id_9f1b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tariff'], name='bot_subscri_tariff__4e2210_idx'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['from_contract'], name='bot_rate_from_co_413fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['to_contract'], name='bot_rate_to_cont_34f390_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('from_contract', 'to_contract')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='bot_payment_user_id_dcad66_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['related_model_type'], name='bot_payment_related_2585c4_idx'),
        ),
    ]
