# Generated by Django 4.2.18 on 2025-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rate_from_contract_rate_to_contract_payment_tariff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription')], default='SUBSCRIPTION', max_length=20),
        ),
    ]
