# Generated by Django 4.2.18 on 2025-02-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
