# Generated by Django 4.2.18 on 2025-02-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_block_error_message_block_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
