# Generated by Django 4.2.18 on 2025-02-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0003_alter_event_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_id',
            new_name='number',
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('contract', 'number')},
        ),
    ]
