# Generated by Django 4.2.18 on 2025-02-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0004_rename_block_id_block_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='indexer.block'),
        ),
    ]
